<?php
include_once('OAuth.php');
session_start();
// Pesapal parameters
$token = $params = null;

// PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your
// developement and  when you are ready to go live change to
// https://www.pesapal.com

// Register a merchant account on demo.pesapal.com and use the merchant key for
// testing. When you are ready to go live make sure you change the key to the
// live account registered on www.pesapal.com
$consumer_key = 'DnvpmbMYmpiF4TbM4+JbWTzGk5zG/8iV';

// Use the secret from your test account on demo.pesapal.com. When you are ready
// to go live make sure you  change the secret to the live account registered on
// www.pesapal.com
$consumer_secret = 'ajHrtXRtcodaQbY2uXivSy4DXE8=';

// Change this to https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you
// are ready to go live
$iframelink = 'https://www.pesapal.com/API/PostPesapalDirectOrderV4';
// $iframelink = 'https://www.pesapal.com/API/PostPesapalDirectOrderV4';
                   
// Get form details
$ticket_option  = $_POST['ticket_option'];
$arr = explode(',', $ticket_option);
$amount         = (integer) $arr[0];
$desc           = $arr[1];
$type           = 'MERCHANT';                       // default value = MERCHANT
$reference      = $_POST['token'];                  // unique order id of the transaction, generated by merchant
$first_name     = $_SESSION['fname'];                 // optional 
$last_name      = $_SESSION['lname'];                  // optional
$email          = $_SESSION['email'];
$phonenumber    = $_SESSION['phone'];                             // ONE of email or phonenumber is required
//echo $first_name, $last_name, $email, $phonenumber;

// Define the callback_url i.e the redirect url, this page that will handle the
// response from pesapal.
$callback_url = 'http://localhost/naidevweek/form-apply/reponse.php';

// The format is standard so no editing is required. Encode the variable using
// htmlentities.
$post_xml = '<?xml version="1.0" encoding="utf-8"?>';
$post_xml .= '<PesapalDirectOrderInfo ';
$post_xml .= 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ';
$post_xml .= 'xmlns:xsd="http://www.w3.org/2001/XMLSchema" ';
$post_xml .= 'Amount="'.$amount.'" ';
$post_xml .= 'Description="'.$desc.'" ';
$post_xml .= 'Type="'.$type.'" ';
$post_xml .= 'Reference="'.$reference.'" ';
$post_xml .= 'FirstName="'.$first_name.'" ';
$post_xml .= 'LastName="'.$last_name.'" ';
$post_xml .= 'Email="'.$email.'" ';
$post_xml .= 'PhoneNumber="'.$phonenumber.'" ';
$post_xml .= 'xmlns="http://www.pesapal.com" />';
$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

// Construct the OAuth Request URL & post transaction to pesapal
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, 'GET', $iframelink, $params);
$iframe_src -> set_parameter('oauth_callback', $callback_url);
$iframe_src -> set_parameter('pesapal_request_data', $post_xml);
$iframe_src -> sign_request($signature_method, $consumer, $token);

// Display pesapal iframe and pass in iframe_src
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
    <meta charset="utf-8">
    <title>Developer Week Nairobi 2016</title>
    <meta content=
    "Developer Week Nairobi 2016 is East Africa's newest tech event series focused on creating world class
    applications."
    name="description">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,  user-scalable=0"/>
    <link href="images/DWN Icon.ico" rel="shortcut icon">
    <link href="images/DWN Icon.ico" rel="icon" type="image/x-icon">

    <link href="../assets/themes/fbf8-live/css/app.css" rel="stylesheet" type="text/css"/>
    <!--[if lte IE 9]>
    <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<!--[if lte IE 9 ]>
<body class="ie register"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<body class="register"> <!--<![endif]-->

    <script>
      var e = document.createElement("script");
      e.async = true;
      e.src = "https://ad.atdmt.com/m/a.js;m=11002203288872;cache=" + Math.random() +
        "?applicant=''";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(e, s);
    </script>
    <noscript>
    <iframe
      style="display:none;"
      src="https://ad.atdmt.com/m/a.html?applicant=">
    </iframe>
    </noscript>

<div class="root">

    <section class="masthead">
        <div class="step-label" style="padding-top: 0px !important">
        <img src="logo.png" width="20%">
            <h5>Complete Ticket Booking</h5>
        </div>
    </section>
    <section class="form-content">
        <div class="container">
            <iframe src="<?php echo $iframe_src; ?>" width="100%" height="800px"  scrolling="no" frameBorder="0">
				<p>Browser unable to load iFrame</p>
			</iframe>
        </div>
    </section>

</div><!-- end root -->

<footer>
    <section class="primary">
        <div class="container">
            <hr>
        </div>
        <div class="container">
            <div class="footer-logo">
                <a href="../" class="abs-mark"><i class="f8-mark-b">Nairobi Developers Week</i></a>
                <h4 class="strong">Nairobi Dev Week 2016</h4>
                <h4>Kenya National Theatre, Nairobi</h4>
                <h4>April 25 - May 1, 2016</h4>
                <div class="fb-share-button" data-href="http://nairobideveloperweek.com/" data-layout="button_count"></div>
            </div>
            <nav>
                <ul>
                    <li><a href="../#how-it-works">Learn more</a></li>
                    <li><a href="../#events">Events</a></li>
                    <li><a href="../#speakers">Speakers</a></li>
                    <li><a href="../#sponsors">Sponsors</a></li>
                    <li><a href="mailto:hello@nairobideveloperweek.com?subject=[web enquiry]">Chat with us</a></li>
                    <li class="active"><a href="#">Register</a></li>
                </ul>
            </nav>
        </div>
    </section>
    <section class="secondary">
        <div class="container">
            <div class="dib pull-left footer-body">
                <span class="fb-dev">&copy; 2016 Nairobi Developers Week</span>
                <span class="dev-links"><a href="https://www.whitehatdev.co">White Hat DEV Team</a> / <a
                        href="#">Facebook Page</a></span>
                <div class="footer-info-links pull-right">
                    <a href="#" class="dib footer-link">FAQs</a>
                    <a href="#" class="dib footer-link">Terms</a>
                    <a href="#" class="dib footer-link">Privacy</a>
                </div>
            </div>
        </div>
    </section>
</footer>

<div class="burger">
    <div class="inner">
        <i class="bar-1"></i>
        <i class="bar-2"></i>
        <i class="bar-3"></i>
    </div>
</div>

<div class="mobile-nav">
    <div class="container">
        <div class="mast">
            <a href="../index.html">
                <i class="f8-mark-w">F8 Facebook Developers Conference</i>
            </a>
        </div>
    </div>
    <nav>
        <ul>
            <li><a href="../#how-it-works">Learn more</a></li>
            <li><a href="../#events">Events</a></li>
            <li><a href="../#speakers">Speakers</a></li>
            <li><a href="../#sponsors">Sponsors</a></li>
            <li><a href="mailto:hello@nairobideveloperweek.com?subject=[web enquiry]">Chat with us</a></li>
            <li class="active"><a href="#">Register</a></li>
        </ul>
    </nav>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="/assets/themes/fbf8-live/js/jquery-1.11.1.js"><\/script>')</script>
<script src="../assets/themes/fbf8-live/js/vendor.js"></script>
<script src="../assets/themes/fbf8-live/js/app.js"></script>
<script src="../assets/themes/fbf8-live/js/checkout.js"></script>
<script>
    WebFont.load({custom: {families: ['Graphik-Regular']}});
    $(function () {
        window.F8_app.init();
    });
</script>
</body>
</html>
<!-- Localized -->