<?php
include_once('OAuth.php');
session_start();
// Pesapal parameters
$token = $params = null;

// PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your
// developement and  when you are ready to go live change to
// https://www.pesapal.com

// Register a merchant account on demo.pesapal.com and use the merchant key for
// testing. When you are ready to go live make sure you change the key to the
// live account registered on www.pesapal.com
$consumer_key = 'DnvpmbMYmpiF4TbM4+JbWTzGk5zG/8iV';

// Use the secret from your test account on demo.pesapal.com. When you are ready
// to go live make sure you  change the secret to the live account registered on
// www.pesapal.com
$consumer_secret = 'ajHrtXRtcodaQbY2uXivSy4DXE8=';

// Change this to https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you
// are ready to go live
$iframelink = 'https://www.pesapal.com/API/PostPesapalDirectOrderV4';
// $iframelink = 'https://www.pesapal.com/API/PostPesapalDirectOrderV4';
                   
// Get form details
$ticket_option  = $_POST['ticket_option'];
$arr = explode(',', $ticket_option);
$amount         = (integer) $arr[0];
$desc           = $arr[1];
$type           = 'MERCHANT';                       // default value = MERCHANT
$reference      = $_POST['token'];                  // unique order id of the transaction, generated by merchant
$first_name     = $_SESSION['fname'];                 // optional 
$last_name      = $_SESSION['lname'];                  // optional
$email          = $_SESSION['email'];
$phonenumber    = $_SESSION['phone'];                             // ONE of email or phonenumber is required
//echo $first_name, $last_name, $email, $phonenumber;

// Define the callback_url i.e the redirect url, this page that will handle the
// response from pesapal.
$callback_url = 'http://localhost/naidevweek/form-apply/reponse.php';

// The format is standard so no editing is required. Encode the variable using
// htmlentities.
$post_xml = '<?xml version="1.0" encoding="utf-8"?>';
$post_xml .= '<PesapalDirectOrderInfo ';
$post_xml .= 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ';
$post_xml .= 'xmlns:xsd="http://www.w3.org/2001/XMLSchema" ';
$post_xml .= 'Amount="'.$amount.'" ';
$post_xml .= 'Description="'.$desc.'" ';
$post_xml .= 'Type="'.$type.'" ';
$post_xml .= 'Reference="'.$reference.'" ';
$post_xml .= 'FirstName="'.$first_name.'" ';
$post_xml .= 'LastName="'.$last_name.'" ';
$post_xml .= 'Email="'.$email.'" ';
$post_xml .= 'PhoneNumber="'.$phonenumber.'" ';
$post_xml .= 'xmlns="http://www.pesapal.com" />';
$post_xml = htmlentities($post_xml);

$consumer = new OAuthConsumer($consumer_key, $consumer_secret);

// Construct the OAuth Request URL & post transaction to pesapal
$signature_method = new OAuthSignatureMethod_HMAC_SHA1();
$iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, 'GET', $iframelink, $params);
$iframe_src -> set_parameter('oauth_callback', $callback_url);
$iframe_src -> set_parameter('pesapal_request_data', $post_xml);
$iframe_src -> sign_request($signature_method, $consumer, $token);

// Display pesapal iframe and pass in iframe_src
?>
<iframe src="<?php echo $iframe_src; ?>" width="100%" height="800px"  scrolling="no" frameBorder="0">
    <p>Browser unable to load iFrame</p>
</iframe>